In [404]:
import pandas as pd
import numpy as np
from sklearn.linear_model import BayesianRidge
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    mean_squared_error,
    r2_score,
    mean_absolute_error,
    confusion_matrix
)
import joblib

In [387]:
'''
df = pd.read_csv('student_data.csv')
df.head()
X = df.drop(columns=['G1', 'G2', 'G3', 'absences', 'exam score'])
y = df['exam score']
X.head()
'''

attendance rate  assessment
0        93.548387           8
1        95.698925           8
2        89.247312          11
3        97.849462          22
4        95.698925          12

In [409]:
'''
# Split data into training set and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

# Select model algorithm to be used
model = BayesianRidge()

# Train the model
model.fit(X_train, y_train)


# Train the model and save it in a file
joblib.dump(model, 'prediction-model.joblib')

# Predict
predictions = model.predict(X_test)

# Calculate evaluation metrics
mse = mean_squared_error(y_test, predictions)
mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mse)
r_squared = r2_score(y_test, predictions)
'''


model = joblib.load('prediction-model.joblib')
prediction = model.predict([ [.9, 5] ])
prediction

C:\Users\seyis\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BayesianRidge was fitted with feature names
  warnings.warn(


array([15.59051613])

In [394]:
prediction = model.predict([ [93, df['assessment'].median()] ])
prediction

C:\Users\seyis\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but BayesianRidge was fitted with feature names
  warnings.warn(


array([38.16953087])

In [272]:
# '''
# Remove pass/fail column from data we give to our model (X) and save it in the expected output(y)
X = df.drop(columns=['pass/fail'])
y = df['pass/fail']

# Split data into training set and testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Select model algorithm to be used
model = KNeighborsRegressor()
model.fit(X_train, y_train)

# Train the model and save it in a file
# joblib.dump(model, 'prediction-model.joblib')

# Predict
predictions = model.predict(X_test)

# Check accuracy levels
score = accuracy_score(y_test,predictions)
score
# '''

# model = joblib.load('prediction-model.joblib')
predictions = model.predict([ [.9, 5, 70] ])
predictions

# tree.export_graphviz(model, out_file='prediction-model.dot',
#                      feature_names=['age', 'gender'], 
#                      class_names=sorted(y.unique()), 
#                      label='all', 
#                      rounded=True,
#                      filled=True)

C:\Users\seyis\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


array([1.])